import { styled } from '@mui/material/styles';
import {
  Table,
  TableBody,
  TableContainer,
  TableHead,
  TableRow,
  Paper,
} from '@mui/material';
import TableCell, { tableCellClasses } from '@mui/material/TableCell';
import { pricesData } from '../../interfaces';
import Head from 'next/head';
import Header from '../../components/Header';

const StyledTableCell = styled(TableCell)(({ theme }) => ({
  [`&.${tableCellClasses.head}`]: {
    backgroundColor: theme.palette.common.black,
    color: theme.palette.common.white,
  },
  [`&.${tableCellClasses.body}`]: {
    fontSize: 14,
  },
}));

const StyledTableRow = styled(TableRow)(({ theme }) => ({
  '&:nth-of-type(odd)': {
    backgroundColor: theme.palette.action.hover,
  },
  // hide last border
  '&:last-child td, &:last-child th': {
    border: 0,
  },
}));

export default function Prices({ data }: pricesData): JSX.Element {
  return (
    <div>
      <Head>
        <title> Prices - Amparo Telefônica</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <TableContainer component={Paper} sx={{ maxWidth: 400 }}>
        <Table sx={{ minWidth: 400 }} aria-label='customized table'>
          <TableHead>
            <TableRow>
              <StyledTableCell align='center'>Origem</StyledTableCell>
              <StyledTableCell align='center'>Destino</StyledTableCell>
              <StyledTableCell align='center'>R$ Por Minuto</StyledTableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {data.map((item) => (
              <StyledTableRow key={item.id}>
                <StyledTableCell align='center'>{item.origem}</StyledTableCell>
                <StyledTableCell align='center'>{item.destino}</StyledTableCell>
                <StyledTableCell align='center'>
                  {item.price.toFixed(2)}
                </StyledTableCell>
              </StyledTableRow>
            ))}
          </TableBody>
        </Table>
      </TableContainer>
    </div>
  );
}

import { GetStaticProps } from 'next';

export const getStaticProps: GetStaticProps = async () => {
  const prices = [
    {
      id: 1,
      origem: '011',
      destino: '016',
      price: 1.9,
    },
    {
      id: 2,
      origem: '011',
      destino: '017',
      price: 1.7,
    },
    {
      id: 3,
      origem: '011',
      destino: '018',
      price: 0.9,
    },
    {
      id: 5,
      origem: '016',
      destino: '011',
      price: 2.9,
    },
    {
      id: 6,
      origem: '017',
      destino: '011',
      price: 2.7,
    },
    {
      id: 7,
      origem: '018',
      destino: '011',
      price: 1.9,
    },
  ];
  return {
    props: {
      data: prices,
    },
    revalidate: 15 * 60 * 60,
  };
};
