import { pricesData } from '../../interfaces';
import Head from 'next/head';
import Header from '../../components/Header';
import Table from './_table';

export default function Prices({ data }: pricesData): JSX.Element {
  return (
    <div>
      <Head>
        <title> Prices - Amparo Telefônica</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Stack gap={3} mt={3}>
        <Typography align='center' variant='h4' color='gray' fontWeight={600}>
          Taxas de ligações intermunicipais
        </Typography>
        <Table data={data} />
      </Stack>
    </div>
  );
}

import { GetServerSideProps } from 'next';
import { Stack, Typography } from '@mui/material';
const URL = process.env.URL || 'https://amparo-telefonica.vercel.app/';

export const getServerSideProps: GetServerSideProps = async () => {
  const response = await fetch(URL + 'prices');
  const data = await response.json();

  return {
    props: {
      data,
    },
  };
};
