import { Button } from '@mui/material';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import Header from '../components/Header';

const Home: NextPage = () => {
  const { push } = useRouter();
  return (
    <div>
      <Head>
        <title> Home - Amparo Telefônica</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='shortcut icon' href='/favicon.ico' />
      </Head>
      <Header />
      <h1>O que deseja fazer?</h1>
      <Button
        size='large'
        variant='contained'
        onClick={() => push('/price-table')}
      >
        Consultar a tabela de preços
      </Button>
      <Button
        size='large'
        variant='contained'
        onClick={() => push('/calculadora')}
      >
        Descobrir quanto economizaria!
      </Button>
    </div>
  );
};

export default Home;
