import { Button } from '@mui/material';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import Header from '../components/Header';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title> Home - Amparo Telefônica</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='shortcut icon' href='/favicon.ico' />
      </Head>
      <Header />
      <div style={{ width: '700px' }}>
        <h1>
          Ligações de um jeito simples e{' '}
          <span style={{ color: 'green' }}>eficiente.</span>
        </h1>
        <p>
          Você está na Amparo Telefônica, uma empresa com diversos planos que
          facilitam e dimui seu custo em ligações. Venha receber um cuidado que
          se encaixe na sua rotina.
        </p>
      </div>
    </div>
  );
};

export default Home;
