import type { NextPage } from 'next';
import Head from 'next/head';

const Calculadora: NextPage = () => {
  return (
    <div>
      <Head>
        <title> Calculadora - Amparo Telefônica</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
    </div>
  );
};

export default Calculadora;
