import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect } from 'react';

const PriceTable: NextPage = () => {
  return (
    <div>
      <Head>
        <title> Home - Amparo Telefônica</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>Price Table</h1>
    </div>
  );
};

export default PriceTable;
