import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect } from 'react';

const Home: NextPage = () => {
  const { push } = useRouter();
  return (
    <div>
      <Head>
        <title> Home - Amparo Telefônica</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>O que deseja fazer?</h1>
      <button onClick={() => push('/price-table')}>
        Consultar a tabela de preços
      </button>
      <button onClick={() => push('/calculadora')}>
        Descobrir quanto economizaria!
      </button>
    </div>
  );
};

export default Home;
