import Head from 'next/head';
import { Box, Stack } from '@mui/material';

import { pricesData } from '../../interfaces';
import Header from '../../components/Header/';
import SelectForm from './_SelectForm';
import Table from './_Table';

export default function Calculadora({ data }: pricesData): JSX.Element {
  return (
    <div>
      <Head>
        <title> Calculadora - Amparo Telefônica</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Box sx={{ display: 'flex', width: '100%', justifyContent: 'center' }}>
        <Stack sx={{ maxWidth: 1200, marginTop: '1rem' }} gap={'2rem'}>
          <h1>Calculadora</h1>
          <SelectForm data={data} />
          <Table />
        </Stack>
      </Box>
    </div>
  );
}

import type { GetServerSideProps } from 'next';

export const getServerSideProps: GetServerSideProps = async () => {
  const response = await fetch('http://localhost:3000/api/prices');
  const data = await response.json();

  return {
    props: {
      data,
    },
  };
};
